### ISSUE TITLE
Gallery layout is different on RTD than in local build

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/metview-docs#1]
This is how it looks on RTD (browser: firefox 93.0):

![image](https://user-images.githubusercontent.com/9033020/137311555-3de6e54e-0c06-4e83-aa0a-8d2c2619ab02.png)

and locally  (browser: firefox 93.0):

![image](https://user-images.githubusercontent.com/9033020/137311814-5b0f8e25-f45c-4d34-b30a-0548e123eaf7.png)

**Comment by sandorkertesz** [comment]
The problem is caused by the docutils version we use. In 0.16.0 it is fine but from version 0.17.0 we get the ugly looking gallery. Until we find a proper solution I restrict the docutils version to <=0.16.0

**Comment by wjjxjd** [comment]
Hello, how can I set the length of the color bar? 
The legend_box_y_length parameter sets the height.

**Comment by wjjxjd** [comment]
Hi, I would like to ask how to set the location of the wind field arrowhead

**Comment by iainrussell** [comment]
Hello @wjjxjd,

Thanks for your interest. Could you post your questions to our support portal please?
https://www.ecmwf.int/en/support

Best regards,
Iain
